apiVersion: v1
kind: Service
metadata:
  name: ts-ext-proxy
  namespace: ts-ext-proxy
spec:
  selector:
    app: ts-ext-proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80