apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-caddyfile
data:
  Caddyfile: |
    # Health check endpoint
    :80 {
        handle /healthz {
            respond "OK" 200
        }
        handle {
            respond "Not found" 404
        }
    }
    {{- $startPort := include "tailscale-external-proxy.startPort" . | int -}}
    {{- range $index, $proxy := .Values.proxies }}
    {{- $currentPort := add $startPort $index }}
    # Proxy for {{ $proxy.hostName }} listening on port {{ $currentPort }}
    :{{ $currentPort }} {
        {{- if $proxy.loggingEnabled }}
        log {
            output stdout
            level INFO
            format console
        }
        {{- end }}
        reverse_proxy {{ $proxy.protocol }}://{{ $proxy.ip }} {
            header_up Host "{{ $proxy.hostName }}.{{ $proxy.domain }}"
            header_up Referer "{{ $proxy.protocol }}://{{ $proxy.hostName }}.{{ $proxy.domain }}"
            {{- if $proxy.insecureSkipVerify }}
            transport http {
                tls_insecure_skip_verify
            }
            {{- end }}
        }
    }
    {{- end }}
