{{- $startPort := include "tailscale-external-proxy.startPort" . | int -}}
{{- range $index, $proxy := .Values.proxies }}
{{- $currentPort := add $startPort $index }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tailscale-external-proxy.fullname" $ }}-{{ $proxy.hostName }}
  labels:
    {{- include "tailscale-external-proxy.labels" $ | nindent 4 }}
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - {{ $proxy.hostName }}
  rules:
    - host: {{ $proxy.hostName }}
      http:
        paths:
          - path:
            pathType: ImplementationSpecific
            backend:
              service:
                name:  {{ include "tailscale-external-proxy.fullname" $ }}
                port:
                  number: {{ $currentPort }}
{{- end }}
