apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tailscale-external-proxy.fullname" . }}
  labels:
    {{- include "tailscale-external-proxy.labels" . | nindent 4 }}
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        {{- range $proxy := .Values.proxies }}
        - {{ $proxy.hostName }}
        {{- end }}
  rules:
    {{- $startPort := include "tailscale-external-proxy.startPort" . | int -}}
    {{- range $index, $proxy := .Values.proxies }}
    {{- $currentPort := add $startPort $index }}
    - host: {{ $proxy.hostName }}
      http:
        paths:
          - path:
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $proxy.hostName }}
                port:
                  number: {{ $currentPort }}
    {{- end }}
